# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.sln'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --no-build'
    projects: 'WebApp-01/WebApp-01.csproj'
  displayName: 'dotnet publish $(buildConfiguration)'

- task: CopyFiles@2  
  inputs:
    sourceFolder: '$(Pipeline.Workspace)/ArmTemplates/bin/Release/'
    contents: 'azuredeploy*.json'
    targetFolder: '$(Pipeline.Workspace)/temparmtemplates/'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/temparmtemplates/'
    artifact: 'armtemplates'
    publishLocation: 'pipeline'
  displayName: 'publish artifacts arm templates'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/WebApp-01/bin/Release/net6.0/publish'
    artifact: 'webapp01'
    publishLocation: 'pipeline'
  displayName: 'publish artifacts webapp-01'

